---
- name: build project
  hosts: all
  remote_user: user
  become: true
  tasks:
    # - name: clone project
    #   git:
    #     repo: https://github.com/Konev-VA/test-ansible-helloworld.git
    #     dest: /home/user/test-ansible-helloworld
    # - name: Hello world
    #   community.docker.docker_container:
    #     name: hello-world
    #     image: hello-world:latest
    #     state: started
    # - name: login to docker
    #   shell: docker login -u konevva -p dckr_pat_JcwVnMqIzZUUfnaFL2inq715jH8
    # - name: login to docker
    #   community.docker.docker_login:
    #     username: konevva
    #     password: dckr_pat_JcwVnMqIzZUUfnaFL2inq715jH8
    #     registry_url: https://hub.docker.com\
    # - name: build project
    #   docker_image:
    #     name: test-ansible-helloworld
    #     build:
    #       path: /home/user/test-ansible-helloworld
    #       args:
    #         listen_port: 8080
    #     source: build
    - name: install nginx
      apt: 
        name: 
          - nginx
        state: latest
        update_cache: yes
    - name: nginx systemd
      systemd:
        name: nginx
        enabled: yes
        state: started