---
- name: build project
  hosts: all
  remote_user: user
  tasks:
    - name: clone project
      git:
        repo: https://github.com/Konev-VA/test-ansible-helloworld.git
        dest: /home/user/test-ansible-helloworld
    - name: login to docker
      community.docker.docker_login:
        username: konevva
        password: dckr_pat_JcwVnMqIzZUUfnaFL2inq715jH8
        registry_url: https://hub.docker.com/repository/docker/konevva/test-ansible-helloworld/